name: seallapp
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - zlib
  - sqlite
  - tk
  - libffi
  - bzip2
  - xz
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - arrow==1.3.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - bibtexparser==1.4.3
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorama==0.4.6
      - deprecated==1.2.18
      - distro==1.9.0
      - dnspython==2.7.0
      - docutils==0.21.2
      - dotenv==0.9.9
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - fake-useragent==2.2.0
      - flask==3.1.1
      - flask-cors==6.0.0
      - flask-pymongo==3.0.1
      - free-proxy==1.1.3
      - frozenlist==1.7.0
      - google==3.0.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1rc0
      - google-api-python-client==2.172.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-genai==1.19.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.0
      - grpcio-status==1.71.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - idna==3.10
      - imagesize==1.4.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.10.0
      - lxml==6.0.0
      - markupsafe==3.0.2
      - multidict==6.6.3
      - numpy==2.2.6
      - openai==1.93.0
      - openpyxl==3.1.5
      - outcome==1.3.0.post0
      - packaging==25.0
      - pandas==2.3.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pycurl==7.45.6
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pymongo==4.13.0
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - requests==2.32.4
      - rsa==4.9.1
      - scholarly==1.7.11
      - selenium==4.34.0
      - six==1.17.0
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - sphinx==8.1.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - tomli==2.2.1
      - tqdm==4.67.1
      - trio==0.30.0
      - trio-websocket==0.12.2
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.4.0
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - wsproto==1.2.0
      - yarl==1.20.1
